name: flutter_phoenix
description: Easily restart your application from scratch, losing any previous state
version: 1.1.1
homepage: https://github.com/mobiten/flutter_phoenix
repository: https://github.com/mobiten/flutter_phoenix
issue_tracker: https://github.com/mobiten/flutter_phoenix/issues

environment:
  sdk: ">=3.2.3 <4.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
